---
openapi: 3.0.3
info:
  title: POS API
  version: v1
servers:
- url: http://localhost:3000
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
- bearerAuth: []
tags:
- name: ReceiptItems
  description: ReceiptItems operations
- name: Receipts
  description: Receipts operations
- name: CartItems
  description: CartItems operations
- name: Carts
  description: Carts operations
- name: SkuMasters
  description: SkuMasters operations
- name: Categories
  description: Categories operations
- name: Users
  description: Users operations
- name: Auth
  description: Auth operations
- name: Payments
  description: Payments operations
- name: Welcome
  description: Welcome operations
paths:
  "/receipt_items/receipt_items_by_receipt":
    get:
      tags:
      - ReceiptItems
      summary: receipt_items_by_receipt action
      responses:
        '200':
          description: Success
  "/receipt_items":
    get:
      tags:
      - ReceiptItems
      summary: index action
      responses:
        '200':
          description: Success
    post:
      tags:
      - ReceiptItems
      summary: create action
      responses:
        '200':
          description: Success
  "/receipt_items/new":
    get:
      tags:
      - ReceiptItems
      summary: new action
      responses:
        '200':
          description: Success
  "/receipt_items/:id/edit":
    get:
      tags:
      - ReceiptItems
      summary: edit action
      responses:
        '200':
          description: Success
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
  "/receipt_items/:id":
    get:
      tags:
      - ReceiptItems
      summary: show action
      responses:
        '200':
          description: Success
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    patch:
      tags:
      - ReceiptItems
      summary: update action
      responses:
        '200':
          description: Success
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    put:
      tags:
      - ReceiptItems
      summary: update action
      responses:
        '200':
          description: Success
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    delete:
      tags:
      - ReceiptItems
      summary: destroy action
      responses:
        '200':
          description: Success
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
  "/receipts/:id/receipt_preview":
    get:
      tags:
      - Receipts
      summary: receipt_preview action
      responses:
        '200':
          description: Success
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
  "/receipts/:id/receipt_pdf":
    get:
      tags:
      - Receipts
      summary: receipt_pdf action
      responses:
        '200':
          description: Success
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
  "/receipts/:id/static_pdf":
    get:
      tags:
      - Receipts
      summary: static_pdf action
      responses:
        '200':
          description: Success
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
  "/receipts":
    get:
      tags:
      - Receipts
      summary: index action
      responses:
        '200':
          description: Success
    post:
      tags:
      - Receipts
      summary: create action
      responses:
        '200':
          description: Success
  "/receipts/new":
    get:
      tags:
      - Receipts
      summary: new action
      responses:
        '200':
          description: Success
  "/receipts/:id/edit":
    get:
      tags:
      - Receipts
      summary: edit action
      responses:
        '200':
          description: Success
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
  "/receipts/:id":
    get:
      tags:
      - Receipts
      summary: show action
      responses:
        '200':
          description: Success
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    patch:
      tags:
      - Receipts
      summary: update action
      responses:
        '200':
          description: Success
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    put:
      tags:
      - Receipts
      summary: update action
      responses:
        '200':
          description: Success
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    delete:
      tags:
      - Receipts
      summary: destroy action
      responses:
        '200':
          description: Success
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
  "/cart_items":
    get:
      tags:
      - CartItems
      summary: index action
      responses:
        '200':
          description: Success
    post:
      tags:
      - CartItems
      summary: create action
      responses:
        '200':
          description: Success
  "/cart_items/new":
    get:
      tags:
      - CartItems
      summary: new action
      responses:
        '200':
          description: Success
  "/cart_items/:id/edit":
    get:
      tags:
      - CartItems
      summary: edit action
      responses:
        '200':
          description: Success
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
  "/cart_items/:id":
    get:
      tags:
      - CartItems
      summary: show action
      responses:
        '200':
          description: Success
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    patch:
      tags:
      - CartItems
      summary: update action
      responses:
        '200':
          description: Success
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    put:
      tags:
      - CartItems
      summary: update action
      responses:
        '200':
          description: Success
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    delete:
      tags:
      - CartItems
      summary: destroy action
      responses:
        '200':
          description: Success
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
  "/carts":
    get:
      tags:
      - Carts
      summary: index action
      responses:
        '200':
          description: Success
    post:
      tags:
      - Carts
      summary: create action
      responses:
        '200':
          description: Success
  "/carts/new":
    get:
      tags:
      - Carts
      summary: new action
      responses:
        '200':
          description: Success
  "/carts/:id/edit":
    get:
      tags:
      - Carts
      summary: edit action
      responses:
        '200':
          description: Success
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
  "/carts/:id":
    get:
      tags:
      - Carts
      summary: show action
      responses:
        '200':
          description: Success
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    patch:
      tags:
      - Carts
      summary: update action
      responses:
        '200':
          description: Success
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    put:
      tags:
      - Carts
      summary: update action
      responses:
        '200':
          description: Success
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    delete:
      tags:
      - Carts
      summary: destroy action
      responses:
        '200':
          description: Success
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
  "/sku_masters/search":
    get:
      tags:
      - SkuMasters
      summary: search action
      responses:
        '200':
          description: Success
  "/sku_masters/by_category":
    get:
      tags:
      - SkuMasters
      summary: by_category action
      responses:
        '200':
          description: Success
  "/sku_masters/sku_master_pagination":
    get:
      tags:
      - SkuMasters
      summary: sku_master_pagination action
      responses:
        '200':
          description: Success
  "/sku_masters":
    get:
      tags:
      - SkuMasters
      summary: index action
      responses:
        '200':
          description: Success
    post:
      tags:
      - SkuMasters
      summary: create action
      responses:
        '200':
          description: Success
  "/sku_masters/new":
    get:
      tags:
      - SkuMasters
      summary: new action
      responses:
        '200':
          description: Success
  "/sku_masters/:id/edit":
    get:
      tags:
      - SkuMasters
      summary: edit action
      responses:
        '200':
          description: Success
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
  "/sku_masters/:id":
    get:
      tags:
      - SkuMasters
      summary: show action
      responses:
        '200':
          description: Success
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    patch:
      tags:
      - SkuMasters
      summary: update action
      responses:
        '200':
          description: Success
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    put:
      tags:
      - SkuMasters
      summary: update action
      responses:
        '200':
          description: Success
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    delete:
      tags:
      - SkuMasters
      summary: destroy action
      responses:
        '200':
          description: Success
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
  "/categories":
    get:
      tags:
      - Categories
      summary: index action
      responses:
        '200':
          description: Success
    post:
      tags:
      - Categories
      summary: create action
      responses:
        '200':
          description: Success
  "/categories/new":
    get:
      tags:
      - Categories
      summary: new action
      responses:
        '200':
          description: Success
  "/categories/:id/edit":
    get:
      tags:
      - Categories
      summary: edit action
      responses:
        '200':
          description: Success
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
  "/categories/:id":
    get:
      tags:
      - Categories
      summary: show action
      responses:
        '200':
          description: Success
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    patch:
      tags:
      - Categories
      summary: update action
      responses:
        '200':
          description: Success
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    put:
      tags:
      - Categories
      summary: update action
      responses:
        '200':
          description: Success
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    delete:
      tags:
      - Categories
      summary: destroy action
      responses:
        '200':
          description: Success
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
  "/users/search":
    get:
      tags:
      - Users
      summary: search action
      responses:
        '200':
          description: Success
  "/users/roles":
    get:
      tags:
      - Users
      summary: roles action
      responses:
        '200':
          description: Success
  "/users":
    get:
      tags:
      - Users
      summary: index action
      responses:
        '200':
          description: Success
    post:
      tags:
      - Users
      summary: create action
      responses:
        '200':
          description: Success
  "/users/new":
    get:
      tags:
      - Users
      summary: new action
      responses:
        '200':
          description: Success
  "/users/:id/edit":
    get:
      tags:
      - Users
      summary: edit action
      responses:
        '200':
          description: Success
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
  "/users/:id":
    get:
      tags:
      - Users
      summary: show action
      responses:
        '200':
          description: Success
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    patch:
      tags:
      - Users
      summary: update action
      responses:
        '200':
          description: Success
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    put:
      tags:
      - Users
      summary: update action
      responses:
        '200':
          description: Success
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    delete:
      tags:
      - Users
      summary: destroy action
      responses:
        '200':
          description: Success
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
  "/login":
    post:
      tags:
      - Auth
      summary: login action
      responses:
        '200':
          description: Success
  "/login/admin":
    post:
      tags:
      - Auth
      summary: login_admin action
      responses:
        '200':
          description: Success
  "/cart_by_user/:user_id":
    get:
      tags:
      - Carts
      summary: cart_by_user action
      responses:
        '200':
          description: Success
  "/payments/cash":
    post:
      tags:
      - Payments
      summary: cash action
      responses:
        '200':
          description: Success
  "/":
    get:
      tags:
      - Welcome
      summary: index action
      responses:
        '200':
          description: Success
